# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'SwiftProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftProject

pod 'SwiftLint'


# keyboard handling
pod 'IQKeyboardManagerSwift'

# loader
pod 'SVProgressHUD'

# Internet checking
pod 'ReachabilitySwift'

# floating lables in textfield
pod 'SkyFloatingLabelTextField'

#---------------------------------------------
# SideMenu
#pod 'SlideMenuControllerSwift'

# lazy loading of images
#pod 'SDWebImage'

# amazon S3 bucket
#pod 'AWSS3'
#pod 'AWSS3', '~> 2.6.13'            # For file transfers

# photo viewer
#pod 'SKPhotoBrowser'

# MultipleimagePicker
#pod 'OpalImagePicker'

# Popover
#pod "Popover"

#crashlytics
#pod 'Fabric'
#pod 'Crashlytics'

end
